debug: false  # 모든 debug 끄기
management.endpoints.web.exposure.include: "*"  # Actuator 중에 드러나지 않은 엔드포인트 볼수 있게 하기

logging:
  level:
    com.example.demo: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # jpa 쿼리문 변수볼수 있게함

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board  # url
    username: yg    # userId
    password: 1234                          # 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver # DB driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: create              # table 자동 생성
    show-sql: true                          # sql 보여누지
    properties:
      hibernate.format_sql: true          # 형식에 맞는 sql보여기
      hibernate.default_batch_fetch_size: 100 # fetch 크기
  sql.init.mode: always                      # data.sql 항상 실행
  data.rest:
    base-path: /api # 기본 경로
    detection-startegy: anotated  # annotation 명시한것만 노출
  thymeleaf3:
    decoupled-logic: true
---

spring:
  config.activate.on-profile: heroku
  datasource:
    url: ${JAWSDB_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa.hibernate.ddl-auto: create
  sql.init.mode: never
